### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by gmanvel** [adamsitnik/StateOfTheDotNetPerformance#1]
Not sure if this is the place to create such issue, but the URL to ndc oslo talk is broken: http://ndcoslo.com/talk/state-of-the-net-performance/
![capture](https://user-images.githubusercontent.com/11509911/50229262-316c1000-03aa-11e9-9f37-f8dc0426a00e.JPG)

I've seen other talk with same title - https://www.youtube.com/watch?v=dVKUYP_YALg 
Maybe you could link to this talk from .NET Summit instead ?

**Comment by adamsitnik** [comment]
@gmanvel  I updated the description of the repo and now it points to the link that you have provided.  thank you!
